### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'X.Bluesky, Version=1.1.5.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by cultpodcasts** [a-gubskiy/X.Bluesky#22]
I have a .Net8 console-application (I am stuck using .Net8 as my main use-case is executing in an Azure Isolated Function)

When I use either 1.1.5-beta or 1.1.4-beta I get the following when I run an application that uses the Package:

**1.1.4-beta:**
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'X.Bluesky, Version=1.1.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'X.Bluesky, Version=1.1.4.0, Culture=neutral, PublicKeyToken=null'
   at XXXXX.Bluesky.Extensions.ServiceCollectionExtensions.AddBlueskyServices(IServiceCollection services, IConfiguration config)
   at Program.<Main>$(String[] args) in C:\Users\jonbr\source\repos\XXXXX\Console-Apps\Poster\Program.cs:line 29
   at Program.<Main>(String[] args)
```
When I examine the bin-folder of the console-application built with 1.1.4-beta there is a file "X.Bluesky.dll" in the bin-folder but it's properties are reported as being version 1.1.3.0

**1.1.5-beta:**
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'X.Bluesky, Version=1.1.5.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'X.Bluesky, Version=1.1.5.0, Culture=neutral, PublicKeyToken=null'
   at XXXXX.Bluesky.Extensions.ServiceCollectionExtensions.AddBlueskyServices(IServiceCollection services, IConfiguration config)
   at Program.<Main>$(String[] args) in C:\Users\jonbr\source\repos\XXXXX\Console-Apps\Poster\Program.cs:line 29
   at Program.<Main>(String[] args)
```
When I examine the bin-folder of the console-application built with 1.1.5-beta there is a file "X.Bluesky.dll" in the bin-folder but it's properties are reported as being version 1.1.4.0

**1.1.3-beta:**
Using 1.1.3-beta does not produce this scenario and the application runs. I see a "X.Bluesky.dll" file in the bin-folder with version reported as version 1.1.5.0

_A manual clean of the application's bin-folder was performed in between each build, using different versions of the package, removing all previous build artifacts._

Thank you for your great work and responsiveness in addressing issues.

**Comment by cultpodcasts** [comment]
Hmm... some funny business on my side. Further examination of the published nupkg file suggests something wrong between my chair and the keyboard and not the package
My apologies. I have a working local build
